{{- if .Values.ingester.enabled }}
{{- $dict := dict "ctx" . "component" "ingester" "memberlist" true -}}
{{- $zonesMap := include "ingester.zoneAwareReplicationMap" $dict | fromYaml -}}
{{- range $zoneName, $rolloutZone := $zonesMap -}}
{{- with $ -}}
{{- $_ := set $dict "rolloutZoneName" $zoneName -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "ingester.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingester.labels" $dict | nindent 4 }}
  {{- if .Values.ingester.zoneAwareReplication.enabled }}
  annotations:
    {{- include "ingester.Annotations" $dict | nindent 4}}
    {{- with $rolloutZone.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else }}
  {{- with .Values.ingester.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if not .Values.ingester.autoscaling.enabled }}
  replicas: {{ $rolloutZone.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.tempo.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ingester.selectorLabels" $dict | nindent 6}}
  serviceName: tempo-ingester
  podManagementPolicy: Parallel
  updateStrategy:
    {{- if .Values.ingester.zoneAwareReplication.enabled }}
    type: OnDelete
    {{- else }}
    {{- toYaml .Values.ingester.statefulStrategy | nindent 4 }}
    {{- end }}
  template:
    {{- include "tempo.podTemplate" (dict
        "ctx" .
        "component" .Values.ingester
        "target" "ingester"
        "rolloutZoneName" $zoneName
        "rolloutZone" $rolloutZone
        "args" (ternary (list (printf "-ingester.availability-zone=%s" $zoneName)) (list) (ne $zoneName ""))
        "persistence" .Values.ingester.persistence
        "dataVolumeName" "data") | nindent 4 }}
  {{- if not .Values.ingester.persistence.enabled }}
  {{- else if .Values.ingester.persistence.inMemory }}
  {{- else }}
  {{- if .Values.ingester.persistentVolumeClaimRetentionPolicy.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.ingester.persistentVolumeClaimRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.ingester.persistentVolumeClaimRetentionPolicy.whenScaled }}
  {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        {{- with .Values.ingester.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.ingester.persistence.labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        name: data
      spec:
        {{- $storageClass := coalesce $rolloutZone.storageClass .Values.ingester.persistence.storageClass .Values.global.storageClass }}
        {{- if eq $storageClass "-" }}
        storageClassName: ""
        {{- else if $storageClass }}
        storageClassName: {{ $storageClass }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.ingester.persistence.size | quote }}
  {{- end }}
---
{{ end }}
{{ end }}
{{- end }}
